version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app.py

  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    working_dir: /app
    command: npm start

networks:
  default:
    driver: bridge 